//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_progra_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int IdPaciente { get; set; }
        public string NombrePaciente { get; set; }
        public string Cedula { get; set; }
        public string Tipo_de_sangre { get; set; }
        public int IdCita { get; set; }
        public bool Eliminado { get; set; }
    }
}
